version: "3"
services:
  postgres:
    container_name: helpdesk_database
    image: postgres:alpine
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  application:
    container_name: helpdesk_application
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
